name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        date=$(date +%s)
        docker build . --file Dockerfile --tag ghcr.io/jmenderle/headlamp:${date}
        docker tag ghcr.io/jmenderle/headlamp:${date} ghcr.io/jmenderle/headlamp:latest
        docker push ghcr.io/jmenderle/headlamp:${date}
        docker push ghcr.io/jmenderle/headlamp:latest
